import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { readMarkdownFile, type FrontMatter } from "@/utils/markdown";
import PageLayout from "@/components/PageLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout() {
  const markdownFiles = await readMarkdownFile();
  const allFrontMatter: FrontMatter[] = markdownFiles.map(
    (file: { frontMatter: FrontMatter }) => file.frontMatter,
  );

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex h-screen overflow-hidden bg-slate-50 font-serif">
          <PageLayout
            allMarkdownData={markdownFiles}
            allFrontMatter={allFrontMatter}
          />
        </div>
      </body>
    </html>
  );
}
